const canvas=document.getElementById('magnetic');const ctx=canvas.getContext('2d');const heroRef=document.getElementById('heroRef');let W,H,DPR,needles=[];let start=performance.now();
function resize(){DPR=Math.min(devicePixelRatio||1,2);W=innerWidth;H=innerHeight;canvas.width=W*DPR;canvas.height=H*DPR;canvas.style.width=W+'px';canvas.style.height=H+'px';ctx.setTransform(DPR,0,0,DPR,0,0);buildNeedles()}window.addEventListener('resize',resize);
function smooth(x){return x*x*(3-2*x)}
function refOpacity(now){const intro=smooth(Math.min(1,now/1.05));const period=16;let p=(now%period)/period;let v;if(p<.24)v=.80*smooth(p/.24);else if(p<.52)v=.80;else if(p<.78)v=.80*(1-smooth((p-.52)/.26));else v=0;return v*intro}
function facePoint(side){const y=H*(.24+Math.random()*.47);const local=(y-H*.24)/(H*.47);const bulge=Math.sin(local*Math.PI);if(side==='left')return{x:W*(.31+Math.random()*.18+bulge*.045)+(Math.random()-.5)*22,y:y+(Math.random()-.5)*24};return{x:W*(.51+Math.random()*.18-bulge*.045)+(Math.random()-.5)*22,y:y+(Math.random()-.5)*24}}
function farPoint(side,origin){const angle=(side==='left'?Math.PI:0)+(Math.random()-.5)*1.35;const len=Math.max(W,H)*(.55+Math.random()*.55);return{x:origin.x+Math.cos(angle)*len,y:origin.y+Math.sin(angle)*len}}
function nearPoint(side,origin){const angle=(side==='left'?0:Math.PI)+(Math.random()-.5)*1.9;const len=Math.min(W,H)*(.07+Math.random()*.22);return{x:origin.x+Math.cos(angle)*len,y:origin.y+Math.sin(angle)*len}}
function oppositePoint(side){return facePoint(side==='left'?'right':'left')}
function makeNeedle(delay){const from=Math.random()<.5?'left':'right';const a=facePoint(from);const r=Math.random();let b,type;if(r<.22){b=farPoint(from,a);type='long'}else if(r<.62){b=nearPoint(from,a);type='short'}else{b=oppositePoint(from);type='bridge'}return{from,a,b,type,delay,life:(type==='long'?8.5:type==='short'?4.6:6.8)+Math.random()*(type==='long'?4.8:3.6),jitter:1.2+Math.random()*3.8,randomPower:(type==='long'?.50:.72)+Math.random()*.38}}
function buildNeedles(){needles=[];let delay=0;for(let i=0;i<30;i++){delay+=.015+Math.random()*.09;if(Math.random()<.32){let burst=2+Math.floor(Math.random()*4);for(let b=0;b<burst;b++)needles.push(makeNeedle(delay+b*(.03+Math.random()*.06)));}else needles.push(makeNeedle(delay));}}
function opacityCurve(p){if(p<0||p>1)return 0;return Math.sin(Math.PI*p)}
function ease(x){return x<.5?2*x*x:1-Math.pow(-2*x+2,2)/2}
function recycle(n,now){Object.assign(n,makeNeedle(now+.15+Math.random()*2.2))}
function draw(ms){const now=(ms-start)*.001;const t=ms*.001;const refA=refOpacity(now);heroRef.style.opacity=refA.toFixed(3);const intro=smooth(Math.min(1,now/1.0));const normalized=Math.max(0,Math.min(1,refA/.80));const master=Math.pow(normalized,1.45)*intro;ctx.clearRect(0,0,W,H);ctx.globalCompositeOperation='lighter';needles.forEach((n,i)=>{if(now<n.delay)return;let p=(now-n.delay)/n.life;if(p>=1){recycle(n,now);return}let localAlpha=opacityCurve(p)*n.randomPower;let alpha=localAlpha*master;let grow=ease(Math.min(1,p/.42));let ax=n.a.x+Math.sin(t*.42+i)*n.jitter;let ay=n.a.y+Math.cos(t*.35+i)*n.jitter*.45;let endX=ax+(n.b.x-ax)*grow;let endY=ay+(n.b.y-ay)*grow;let widthBase=n.type==='long'?.20:n.type==='short'?.24:.30;let widthAmp=n.type==='long'?.28:n.type==='short'?.30:.46;let alphaScale=n.type==='long'?.24:n.type==='short'?.30:.36;ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(endX,endY);ctx.strokeStyle=`rgba(232,213,168,${alpha*alphaScale})`;ctx.lineWidth=widthBase+alpha*widthAmp;ctx.stroke();ctx.beginPath();ctx.moveTo(ax,ay);ctx.lineTo(endX,endY);ctx.strokeStyle=`rgba(255,236,190,${alpha*.038})`;ctx.lineWidth=n.type==='long'?.55:.72;ctx.stroke();const tip=.38+alpha*(n.type==='long'?.95:1.25);ctx.beginPath();ctx.arc(endX,endY,tip,0,Math.PI*2);ctx.fillStyle=`rgba(232,213,168,${alpha*.26})`;ctx.fill();});requestAnimationFrame(draw)}resize();requestAnimationFrame(draw);
